# Generated by Django 5.2.1 on 2025-06-29 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('birthday', models.DateField(null=True)),
                ('phone', models.CharField(max_length=12)),
                ('payed', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('MN', 'Erkak'), ('WN', 'Ayol'), ('OT', 'Boshqa')], default='MN', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('total_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed_points', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
